file-version: 1
############################################################
# +------------------------------------------------------+ #
# |              Recuros Adicionais (Addons)             | #
# +------------------------------------------------------+ #
############################################################
AtivarAddons:
  massiveFactions: true
  Legendchat: true
  mcMMO: true

############################################################
# +------------------------------------------------------+ #
# |                  Recursos Anti-BUG                   | #
# +------------------------------------------------------+ #
############################################################
Bloquear-Cama: true
Bloquear-Subir-Em-Veiculos: true
Bloquear-NameTag: true
Bloquear-Passar-Da-Borda: true
Bloquear-Subir-No-Teto-Nether: true
EnderPearl-Cooldown: 
  Ativar: true
  Cooldown: 5

Bloquear-Abrir-Containers: 
  Ativar: false
  Containers:
  - 'ANVIL'
  - 'ENCHANTING'
  - 'HOPPER'
  # Lista de containers da 1.8: http://docs.codelanx.com/Bukkit/1.8/org/bukkit/event/inventory/InventoryType.html

Bloquear-Shift-Em-Containers:
  Ativar: false
  Containers:
  - 'ENDER_CHEST'
  - 'BEACON'
  - 'BREWING'
  # Lista de containers da 1.8: http://docs.codelanx.com/Bukkit/1.8/org/bukkit/event/inventory/InventoryType.html

# É recomedando ativar isto para quem usa o BlackMarket ou BlackEconomy... 
# Isto previne o bug do valor NaN ou null
Bloquear-Money-Invalido: false
Comandos-Que-Envolvem-Money:
  - 'coins'
  - 'money'
  - 'mercado'
  - 'eco'
  - 'pay'

############################################################
# +------------------------------------------------------+ #
# |             Desativar Recursos do Mapa               | #
# +------------------------------------------------------+ #
############################################################
Bloquear-Congelar-Agua: false
Bloquear-Derreter-Gelo-E-Neve: false
Desativar-Ciclo-Do-Dia: true
Desativar-Dano-Do-EnderDragon: false
Desativar-Dano-Do-Whither: true
Desativar-Mobs-Naturais: true
Desativar-Propagacao-Do-Fogo: true
Desativar-Queda-Das-Folhas: false
Desativar-Queda-Da-Areia: false
Desativar-Flow-Da-Agua-E-Lava: false
Desativar-Chuva: true

############################################################
# +------------------------------------------------------+ #
# |                   Recursos Gerais                    | #
# +------------------------------------------------------+ #
############################################################
Bigorna-Infinita: true
Ativar-Cores-Na-Bigorna: true
Ativar-Cores-Na-Placa: true
Bloquear-Cair-No-Void: true
Bloquear-Mobs-De-Pegarem-Fogo-Para-O-Sol: false
Desativar-Fome-Nos-Mundos: true
Desativar-Mensagem-De-Entrada: true
Desativar-Mensagem-De-Morte: true
Desativar-Mensagem-De-Saida: true
Entrar-No-Spawn-Ao-Logar: true
Bloquear-Criar-Portal: true
Bloquear-Teleport-Por-Portal:
  Ativar: true
  NetherPortal: true
  EndPortal: false

############################################################
# +------------------------------------------------------+ #
# |                Configurações Diversas                | #
# +------------------------------------------------------+ #
############################################################
Delay-Para-Teleportar-Comandos: 5

Tempo-Para-Expirar-Solicitacao-Tpa: 60
Tempo-Para-Poder-Enviar-Outra-Solicitacao-Tpa: 30

Limitador-De-Players:
  Ativar: true

  # Não se esqueça de alterar o limite de players na server.propriets
  # Se você colocar limite de 300 deixe pelo menos umas 20 vagas para VIPS
  # Então coloque 320 na server.propriets
  Limite-De-Players: 300

  # Se o servidor estiver lotado, deseja kickar um player aleatório
  # sem vip para que um vip possa entrar?
  Kickar-Sem-Vip: true
  Tempo-Para-Ser-Kickado-Apos-Aviso: 60 #segundos

Invencibilidade-Ao-Teleportar: 
  Ativar: true
  Tempo-De-Invencibilidade-Ao-Teleportar: 3

Dropar-Cabeca-Ao-Morrer: 
  Ativar: true
  Chance-De-Dropar-Cabeca-Ao-Morrer: 15

Sistema-De-Fly-Para-Players: true
Mundos-Onde-Pode-Usar-Fly:
  - 'world'
  - 'world_nether'


############################################################
# +------------------------------------------------------+ #
# |                 Sistemas de Spawners                 | #
# +------------------------------------------------------+ #
############################################################
Sistema-De-Spawners: true
Bloquear-Trocar-Tipo-Do-Spawner-Com-Ovo: true
Dropar-Spawner-Ao-Explodir: true
Chance-De-Dropar-Ao-Explodir: 60

############################################################
# +------------------------------------------------------+ #
# |           Mensagem e Title de Boas-Vindas            | #
# +------------------------------------------------------+ #
############################################################
Mensagem-De-Boas-Vindas:
  Ativar: false
  Mensagem:
    - '&6-&e=&6-&e=&6-&e=&6-&e=&6-{ &bSeja Bem Vindo ao Hypixel! &6}-&e=&6-&e=&6-&e=&6-&e=&6-'
    - '&eAdquira CASH e VIP em: &6store.hypixel.net'
    - '&eNos siga no twiiter: &6twiiter.com/hypixel'
    - '&eDivirta-se em nosso TS3: &6ts.hypixel.net'
    # %player% mostra o nome do player.

Title-De-Boas-Vindas:
  Ativar: true
  Titulo: '&6&lHYPIXEL'
  Subtitulo: '&eSEJA BEM-VINDO!'
  # %player% mostra o nome do player.

############################################################
# +------------------------------------------------------+ #
# |                 Mundo VIP do Servidor                | #
# +------------------------------------------------------+ #
############################################################
Ativar-Camarote-Para-Os-Sem-Vip: true

############################################################
# +------------------------------------------------------+ #
# |                   Motd do Servidor                   | #
# +------------------------------------------------------+ #
############################################################
Motd:
  Ativar: true
  Linha1: "&f&lGamer's&6&lBoard &7www.gamersboard.com.br"
  Linha2: "&fA sua comunidade gamer!"

############################################################
# +------------------------------------------------------+ #
# |                   Bloquear Comandos                  | #
# +------------------------------------------------------+ #
############################################################
Bloquear-Comandos: false
Lista-Dos-Comandos-Bloqueados:
  - '/teste'
  - '/dupar'
  - '/pl'
  - '/plugins'
 
############################################################
# +------------------------------------------------------+ #
# |                    Bloquear Crafts                   | #
# +------------------------------------------------------+ #
############################################################
Bloquear-Crafts: true
Lista-Dos-Crafts-Bloqueados: 
  - '333'
  - '321'
  - '416'
  - '328'
  # Lista de IDs da 1.8: https://www.minecraftinfo.com/idlist.htm

############################################################
# +------------------------------------------------------+ #
# |                    Bloquear Placas                   | #
# +------------------------------------------------------+ #
############################################################
Bloquear-Palavras-Em-Placas:
  Ativar: true
  Bloquear-Todas-As-Palavras: false
  Bloquear-Apenas-Algumas-Palavras: true
  Lista-Das-Palavras-Bloqueadas:
    - 'AdminShop'
    - '&0AdminShop'
    - 'puta'

############################################################
# +------------------------------------------------------+ #
# |               Bloquear Nicks Impróprios              | #
# +------------------------------------------------------+ #
############################################################
Bloquear-Nicks-Improprios: true
Nicks-Bloqueados:
  - 'puta'
  - 'vadia'
  - 'AdminShop'
  - 'ServerAdmin'
  # O bloqueador verifica se o nick contem tal palavra.
  # Ou seja se o nick do player contem a palavra "puta" o player é bloqueado de entrar.

############################################################
# +------------------------------------------------------+ #
# |                  Comando /slime                      | #
# +------------------------------------------------------+ #
############################################################
Commando-Slime:
  Esta-Em-SlimeChunk: SLIME_WALK2
  Nao-Esta-Em-SlimeChunk: VILLAGER_NO
  
############################################################
# +------------------------------------------------------+ #
# |                         mcMMO                        | #
# +------------------------------------------------------+ #
############################################################
#Tag no legendchat {mctop}
#Para os nomes das skills ficarem em BR vc precisa estar usando um mcMMO traduzido
mcTopTag:
  Tempo-De-Checagem: 300
  Tag: '&9[⚒] '

############################################################
# +------------------------------------------------------+ #
# |                      LegendChat                      | #
# +------------------------------------------------------+ #
############################################################
CorAutomatica:
  master: "§6"
  gerente: "§4"
  admin: "§c"
  vip1: "§2"
  vip2: "§e"
  #Permissão para escrever em destaque no /g: system.chat.destaque
  #Permissão para usar a cor automatica nas frases: system.chat.cor.<cor> 
  #Exemplo: system.chat.cor.master system.chat.cor.vip1

############################################################
# +------------------------------------------------------+ #
# |                     Auto-Anunciar                    | #
# +------------------------------------------------------+ #
############################################################
Auto-Anuncio: true
Destacar-Anuncio: true
Delay-Entre-Anuncios: 300
Reproduzir-Som-No-Anuncio: true
Som-Do-Anuncio: LEVEL_UP
# Lista de sons do minecraft 1.8 http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html
Lista-De-Anuncios:
  - '&e&l[Anuncio] &eInscreva-se em nosso canal e fique por dentro de tudo &b&nhttp://bit.ly/hypixel&e!'
  - '&e&l[Anuncio] &eAdquira já seu vip através do nosso site &b&nhttps://hypixel.net/&e!'
  - '&e&l[Anuncio] &eAcesse já nosso fórum e fique por dentro de tudo &b&nhttps://hypixel.net/forums/&e!'
  - '&e&l[Anuncio] &eO evento karaoke ira ocorrer nesta semana! Saiba mais &b&nhttp://bit.ly/karaoke&e!'

############################################################
# +------------------------------------------------------+ #
# |                     Anunciar Morte                   | #
# +------------------------------------------------------+ #
############################################################
Anunciar-Morte: true
Anuncios: 
  Mostrar-Para-Quem-Morreu: true
  Mensagem-Para-Defunto: "&cVocê foi porto por %playerMatou%!"

  Mostrar-Para-Quem-Matou: true
  Mensagem-Para-Matador: "&cVocê matou o player %playerMorreu%!"

  Mostrar-Para-Todo-Servidor: false
  Mensagem-Para-Todos: "&c%playerMorreu% foi morto por %playerMatou%!"

############################################################
# +------------------------------------------------------+ #
# |                      ScoreBoard                      | #
# +------------------------------------------------------+ #
############################################################
ScoreBoard:
  # A scoreboard não possui variaveis.
  Ativar: true
  Titulo: "  &6&lHypixel  "
  Linhas:
  - '&eSeja Bem Vindo!'
  - '&r'
  - '&aAdquira VIP e Cash:'
  - '&7store.hypixel.net'

############################################################
# +------------------------------------------------------+ #
# |                       Tablist                        | #
# +------------------------------------------------------+ #
############################################################
Ativar-Tablist: true
Parte-De-Cima: |
  &r 
  &r 
  &6&lHYPIXEL
  &f    hypixel.net
Parte-De-Baixo: |
  &r 
  &6Fórum:&f hypixel.net/forums
  &6Team Speak:&f ts.hypixel.net
  &6Facebook:&f fb.com/Hypixel
  &6Twiiter:&f twitter.com/hypixel
  &r
  &6Adquira VIP e Cash acessando: &fstore.hypixel.net
  &r